services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\LocationPosts\ConditionalOnComponent\Users\FieldResolvers\:
        resource: '../../../src/ConditionalOnComponent/Users/FieldResolvers/*'
