services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\LocationPosts\ConditionalOnComponent\Tags\FieldResolvers\:
        resource: '../../../src/ConditionalOnComponent/Tags/FieldResolvers/*'
