services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\LocationPosts\ConditionalOnContext\AddLocationPostTypeToCustomPostUnionTypes\SchemaServices\:
        resource: '../../../src/ConditionalOnContext/AddLocationPostTypeToCustomPostUnionTypes/SchemaServices/*'
